name: Plik

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Codziennie o północy w niedzielę

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Debug info
        run: |
          python --version
          pip --version
          pyinstaller --version

      - name: Install dependencies
        run: |
          pip install pyinstaller
          .\installResources.ps1

      - name: Build executable
        run: pyinstaller --onefile program.py

      - name: Display dist folder contents
        run: dir dist

      - name: Run program
        run: |
          cd dist
          program.exe

