name: Plik 

on:  
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Codziennie o północy w niedzielę

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GH_DOTCOM_TOKEN }}
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g pyinstaller
          .\installResources.ps1

      - name: Build executable
        run: pyinstaller --onefile program.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: program-exe
          path: dist/program.exe
